/**
 * Image optimization utilities for generating responsive image URLs
 * and attributes for modern image formats (AVIF, WebP, JPG)
 */

// Available image widths generated by the optimization script
export const IMAGE_SIZES = [320, 640, 768, 1024, 1280, 1920] as const;

export type ImageFormat = 'avif' | 'webp' | 'jpg';

/**
 * Get the optimized image path for a given source image
 * @param src - Original image path (e.g., '/assets/hero.jpg')
 * @param width - Desired width (optional, uses full size if not specified)
 * @param format - Image format (avif, webp, or jpg)
 * @returns Optimized image path
 */
export function getOptimizedImagePath(
  src: string,
  width?: number,
  format: ImageFormat = 'jpg'
): string {
  // Extract filename without extension
  const pathParts = src.split('/');
  const filename = pathParts[pathParts.length - 1];
  const nameWithoutExt = filename.replace(/\.(jpg|jpeg|png|webp)$/i, '');
  
  // Build optimized path
  const basePath = '/assets/optimized';
  
  if (width) {
    return `${basePath}/${nameWithoutExt}-${width}w.${format}`;
  }
  
  return `${basePath}/${nameWithoutExt}.${format}`;
}

/**
 * Generate srcset string for responsive images
 * @param src - Original image path
 * @param format - Image format
 * @param maxWidth - Maximum width to generate (optional)
 * @returns srcset string
 */
export function generateSrcSet(
  src: string,
  format: ImageFormat = 'jpg',
  maxWidth?: number
): string {
  const sizes = maxWidth
    ? IMAGE_SIZES.filter((size) => size <= maxWidth)
    : IMAGE_SIZES;
  
  return sizes
    .map((width) => {
      const path = getOptimizedImagePath(src, width, format);
      return `${path} ${width}w`;
    })
    .join(', ');
}

/**
 * Calculate the sizes attribute for responsive images
 * This helps the browser select the appropriate image size
 * 
 * @param breakpoints - Object with breakpoint sizes
 * @returns sizes attribute string
 * 
 * @example
 * calculateSizes({
 *   mobile: '100vw',
 *   tablet: '50vw',
 *   desktop: '33vw'
 * })
 * // Returns: "(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 33vw"
 */
export function calculateSizes(breakpoints: {
  mobile?: string;
  tablet?: string;
  desktop?: string;
}): string {
  const { mobile = '100vw', tablet, desktop } = breakpoints;
  
  const sizesArray: string[] = [];
  
  if (tablet) {
    sizesArray.push(`(max-width: 768px) ${mobile}`);
    if (desktop) {
      sizesArray.push(`(max-width: 1024px) ${tablet}`);
      sizesArray.push(desktop);
    } else {
      sizesArray.push(tablet);
    }
  } else if (desktop) {
    sizesArray.push(`(max-width: 1024px) ${mobile}`);
    sizesArray.push(desktop);
  } else {
    return mobile;
  }
  
  return sizesArray.join(', ');
}

/**
 * Get common sizes attribute for typical use cases
 */
export const COMMON_SIZES = {
  // Full width on all devices
  fullWidth: '100vw',
  
  // Hero images - full width on mobile, 80% on desktop
  hero: '(max-width: 768px) 100vw, 80vw',
  
  // Content images - full width on mobile, half on tablet, third on desktop
  content: '(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 33vw',
  
  // Grid images - half width on mobile, third on tablet, quarter on desktop
  grid: '(max-width: 768px) 50vw, (max-width: 1024px) 33vw, 25vw',
  
  // Thumbnail images - fixed small size
  thumbnail: '(max-width: 768px) 150px, 200px',
  
  // Service cards - full on mobile, half on tablet, third on desktop
  serviceCard: '(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw',
};

/**
 * Extract dimensions from image filename if present
 * Some images might have dimensions in their name like "image-800x600.jpg"
 */
export function extractDimensionsFromFilename(filename: string): {
  width?: number;
  height?: number;
} {
  const match = filename.match(/(\d+)x(\d+)/);
  if (match) {
    return {
      width: parseInt(match[1], 10),
      height: parseInt(match[2], 10),
    };
  }
  return {};
}

/**
 * Calculate aspect ratio from width and height
 */
export function calculateAspectRatio(width: number, height: number): number {
  return width / height;
}

/**
 * Get responsive width based on aspect ratio
 */
export function getResponsiveHeight(
  width: number,
  aspectRatio: number
): number {
  return Math.round(width / aspectRatio);
}
